#! /bin/bash
# @edt OriolGalvez
# Febrer 2021
# Validar hi ha un argument.
# Si l'arhgument es un directori. Si no es directori error.
# Llistarlo
#       validar Earg, Validar [0-10]
#       $ prog nota
# ------------------------------------------
ERR_NARGS=1
ERR_CONDS=2
# 1) Validar arguments
if [ $# -ne 1 ]
then
    echo "Error: nª arguments incorrecte"
    echo "Usage: $0 nota"
    exit $ERR_NARGS
fi
nom=$1
if  [ $nom -d ] 
then
    echo "$nom es un directori"
    exit 0
fi
if  [ $nom -h ] 
then
    echo "$nom es un link"
    exit 0
if  [ $nom -f ] 
then
    echo "$nom es un regular file"
    exit 0
if  [ $nom ! -d -a $nom ! -h -a $nom ! -f] 
then
    echo "$nom no valida cap condicio"
    exit $ERR_CONDS
